[catalogue]
catalogue.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[redis]
redis.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[user]
user.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[cart]
cart.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[rabbitmq]
rabbitmq.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[shipping]
shipping.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[mysql]
mysql.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321

[payment]
payment.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321s

[mongodb]
mongodb.vkdevin.online ansible_user=ec2-user ansible_password=DevOps321




