- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy: # so Here we are copying data so we use this module 
      src: mongo.repo #source : from where 
      dest: /etc/yum.repos.d/mongo.repo  #dest : destination =  Copy to where.

  - name: Install mongodb server
    ansible.builtin.dnf: # installation module 
      name: mongodb-org
      state: present # we can use present or installed both will work 
  
  - name: start and enable mongodb
    ansible.builtin.service: # this module for  start and enable 
      name: mongod
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:  # phere we use this module to replace the  data 
      path: /etc/mongod.conf
      regexp: '127.0.0.1' # existed content
      replace: '0.0.0.0' # which we have to change 

  - name: restart mongodb #  restart module
    ansible.builtin.service:
      name: mongod
      state: restarted

#  #---------------output----------

# # # So If we use below command then then it will run in background it just gives 4 digits number.like "14564"

# #  nohup ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 mongodb.yaml  &>> /home/ec2-user/mongo.db.log &

# # [1] 14564

# -----------------------------------------------------
# To check how its doing the given task use "tail -f logfile"
# example : tail -f  /home/ec2-user/mongo.db.log &     ------> this is the command 
# [1] 14701

# TASK [allow remote connections] ************************************************
# changed: [mongodb.vkdevin.online]

# TASK [restart mongodb] *********************************************************
# changed: [mongodb.vkdevin.online]

# PLAY RECAP *********************************************************************
# mongodb.vkdevin.online     : ok=6    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
