
- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - maven
    - mysql
    
  - name: install PyMySQL and cryptography 
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: extract shipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  # - name: connect to mysql using app user
  #   community.mysql.mysql_info:
  #     login_user: shipping
  #     login_password: RoboShop@1
  #     login_host: mysql.daws84s.site
  #     login_db: cities

  - name: import data
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.vkdevin.online
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping

  
  # --TAGS------►KEYWORD

# # Here we used tags to dont repeat code from the starting while doing i got an error in thiis line so if i do changes and run it in linux server it will run the playbook from first it will be soo waste of time soo better you can use tags module

# # so here we used tags:
#                    # - import   ---its a name of our tag .
# # so if u run in linux server using tags :
# command should be : ansible-playbook -i inventory.ini -e ansible_user=ec2-user ansible_password=DevOps321 shipping.yaml --tags "import" 

# # So if we run like this it will run from their only soo here  we used it in 12 task check.

## ags must be at the same level as name and the module, not nested under the module.
# - name: import data
#  tags: 
#   - import
#   community.mysql.mysql_db:
#      name: all
#      login_user: root